### ISSUE TITLE
Support non ansi character sets when converting hex codes to characters

### ISSUE THREAD

**Issue by zoehneto** [tbluemel/rtf.js#1]
The parser currently only supports the ansi charset, which leads to wrong hex code conversion when using the mac charset. For example the codes 0xD4 (212, left quote) and 0xD5 (213, right quote) actually correspond to ansi characters 145 and 146 which leads to text with wrong characters.

**Comment by tbluemel** [comment]
I know, code page support hasn't been implemented.  Do you have a patch and/or simple test document by chance?

**Comment by zoehneto** [comment]
I'm currently using http://www.scottlynch.us/files/rsurs-sample.rtf for testing my implementation and all characters are displayed correctly with the patch.
