### ISSUE TITLE
Unable to Render Data from XMLHttpRequest

### ISSUE THREAD

**Issue by tclancy** [tbluemel/rtf.js#13]
I'm working on a [Chrome extension to read RTF files directly](https://github.com/tclancy/rtfextension) but I am running into an error when I try to [render a file in the browser](https://github.com/tclancy/rtfextension/blob/master/reader.js#L44). I'm using [this file](http://thewalter.net/stef/software/rtfx/sample.rtf) for testing and it works when I drag and drop it into your demo page but I get `Not a valid rtf document` when I send the contents directly to `RTFJS.Document`-- if I log the contents to the console and compare them to the file itself in a diff viewer I don't see any differences. I've also tried using the `.response` and `.responseText` properties of the `XMLHttpRequest` without any difference. Am I improperly instantiating the `RTFJS.Document` object, is this an encoding issue or something else?

**Comment by zoehneto** [comment]
I have implemented a chrome extension for displaying rtf with rtf.js at zoehneto/chrome-rtf-viewer. The key is to convert the responseText to a UInt8 array before passing it to rtf.js.

**Comment by tclancy** [comment]
Ah, thanks so much. Wish I had seen your extension before I started. Is it available in the Chrome store?

**Comment by zoehneto** [comment]
No, you have to clone the repo and install it via development mode.

**Comment by tclancy** [comment]
Would you be ok with me submitting it to the Chrome Store, giving full credit to you (or however you want to handle it)? I have a client who needs to be able to read RTF files on a number of Chromebooks and setting them all to Development Mode isn't feasible (it's not just the browser, but the OS itself that needs to be set to Development on Chromebooks).

**Comment by zoehneto** [comment]
In general I would be fine with that, i'm going to write you a mail so we can discuss this further.

**Comment by zoehneto** [comment]
The extension is now available in the chrome store at https://chrome.google.com/webstore/detail/rtf-viewer/djalaeippddcgflofefafkgijpefkjef

**Comment by tbluemel** [comment]
Nice! Btw, Tom, I granted you push rights because I don't always have the time to deal with pull requests ;-)

**Comment by zoehneto** [comment]
Thank you very much :)

**Comment by tclancy** [comment]
I guess this is ok to close, thanks to everyone.
