### ISSUE TITLE
BlackBerry Playbook - unable to parse doc

### ISSUE THREAD

**Issue by TyronneWayne** [tbluemel/rtf.js#20]
On blackberry playbook the ajax request (in loadRtfFile) never enters in success callback
*ajax requests for different datatypes are ok

**Comment by zoehneto** [comment]
Does it enter the error callback instead and if so, what is the error (should be shown on the page)? If the error callback isn't called either, I would take a look at the `jquery.binarytransport.js` script and see whether the first if block is ever entered. If not it is probably an issue with your browser not supporting `Blob` or `ArrayBuffer`.

**Comment by TyronneWayne** [comment]
No - it does not enter in the error callback either. BB playbook uses its own inbuild browser - no idea what is the name. I tested on Dolphin browser on the same device - it entered in the error callback with error: No conversion from text to binary.

**Comment by zoehneto** [comment]
Since I don't have a BB playbook I can't test this, but you could try changing the `loadRtfFile` function to something like this:

```
function stringToBinaryArray(string) {
    var buffer = new ArrayBuffer(string.length);
    var bufferView = new Uint8Array(buffer);
    for (var i=0; i<string.length; i++) {
        bufferView[i] = string.charCodeAt(i);
    }
    return buffer;
}

function loadRtfFile(file) {
	beginLoading();
	$.ajax({
		url: file,
		dataType: "text",
		processData: false,
		success: function(result) {
			displayRtfFile(stringToBinaryArray(result));
		},
		error: function(jqXHR, textStatus, errorThrown) {
			$("#content").text("Error: " + errorThrown);
		}
	});
}
```

This should work in the dolphin browser, as long as `ArrayBuffer` is supported.

**Comment by TyronneWayne** [comment]
Same result.
It is a bit outdated device so I assume we have to blame the browser and BlackBerry - more or less they are out of the phone/tablet market.
Anyhow, good job man this project is an incredible product and it saved me so match troubles.(for a developer the marketing department is a nightmare to work with)

**Comment by zoehneto** [comment]
Thanks, just to clarify, you still get the same error message after you changed the code locally?

**Comment by TyronneWayne** [comment]
Yes - dolphin browser still fails to load rtf content - the label stays with "Loading..." text. (cache cleared)
Native browser is now OK (I probably forgot to clear the cache last night or messed up something on deploy).
Unfortunately I can not debug on this device - I can only observe the result.
