### ISSUE TITLE
Unable to parse Chinese

### ISSUE THREAD

**Issue by TangentLu666** [tbluemel/rtf.js#25]
Unable to parse Chinese，Can you tell me where to fix it?
Thank you!
![image](http://upload-images.jianshu.io/upload_images/1498308-f50d3e430a6fa272.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by zoehneto** [comment]
Can you post a sample file with this issue? This should not happen since we support both UTF-8 and many specific codepages. I have definitely seen it work with other asian languages.

**Comment by zoehneto** [comment]
I have just committed a fix which adds support for double width characters as used by Chinese and other Asian languages. It's not perfect yet, as it only supports the document body, not the metadata fields.

**Comment by TangentLu666** [comment]
thank you ！
