### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by zoehneto** [tbluemel/rtf.js#34]
Since I added a test setup, it would be really nice if the test suite was run for every PR using some continuous integration system like travis ci. That way we could ensure whatever is being committed using a PR doesn't break users. 

@tbluemel since you are the [repository owner](https://help.github.com/articles/permission-levels-for-a-user-account-repository/) only you can make these kinds of changes, would you be interested in looking into this?

**Comment by tbluemel** [comment]
I added Travis CI, if there is anything else I need to configure or do to make it work, let me know.

**Comment by zoehneto** [comment]
That's all, I added the `.travis.yml` config file and also rebased my typescript PR, you can see the result there.
