### ISSUE TITLE
Coverage reporting

### ISSUE THREAD

**Issue by zoehneto** [tbluemel/rtf.js#36]
@tbluemel I just added coverage reporting for our test suite. Could you please enable [coveralls](https://coveralls.io) so we can get coverage reporting for PRs etc.? When you have added coveralls I can do the rest of the setup (sending coverage info from travis ci to coveralls.

**Comment by tbluemel** [comment]
Should be enabled.  Let me know if there's anything else I need to do.

**Comment by zoehneto** [comment]
Thank you, I just made the required changes and added a badge to the README.
