### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by zoehneto** [tbluemel/rtf.js#38]
@tbluemel I have just published the latest version of rtf.js to npm to make it easier to use with modern projects. You can find it at https://www.npmjs.com/package/rtf.js . If you create an account as described [here](https://docs.npmjs.com/cli/adduser) I can give you the permissions to publish packages.

**Comment by tbluemel** [comment]
Nice!  I created a user with the same name as here.

**Comment by zoehneto** [comment]
I just added you as an owner.
