### ISSUE TITLE
WMF files with vector graphics are not rendered by wmf.js

### ISSUE THREAD

**Issue by zoehneto** [tbluemel/rtf.js#4]
WMF files with embedded bitmaps (for example in simplepict.rtf in the sample folder) are displayed correctly, while vector graphics are not displayed (generated svg is empty).

Link to test file :https://www.dropbox.com/s/0qp9gpe2ox93to5/minimal-image.rtf?dl=0

**Comment by tbluemel** [comment]
Yes, wmf.js is in it's infancy state.  What you can see in the sample folder is about all it supports right now.

**Comment by tbluemel** [comment]
I made a bunch of changes today that are relevant to this particular file.  I got all the way to adding a rectangle function, which somehow doesn't produce the expected result, though.  There were numerous bugs in other places, so you might want to check out what I committed so far.

**Comment by zoehneto** [comment]
Thanks for the update. The reason your rectangles don't work is, that you nest them in an additional svg element with incorrect viewBox attribute. If you remove the nested svg elements or set their viewBox to the same value as the parent the rectangles are displayed correctly.

**Comment by tbluemel** [comment]
Thanks, I fixed it, rectangles get rendered correctly now :-)

**Comment by tbluemel** [comment]
I just added some rudimentary support to draw lines and render text, looking much better already!

**Comment by zoehneto** [comment]
Looks great, I think the only thing missing for this image now is support for polygons.

**Comment by zoehneto** [comment]
This is the full file the original image is from, which also contains some more complicated images for testing: https://www.dropbox.com/s/vq242m8udpdya7w/jrg003.rtf?dl=0

**Comment by tbluemel** [comment]
Added polygons, aside from it being bare minimum for this particular image, it looks almost perfect :)

**Comment by tbluemel** [comment]
Added support for rotated text as well

**Comment by tbluemel** [comment]
I just added poly-polygon support and it's amazing how complex artwork it can all the sudden render!

**Comment by zoehneto** [comment]
Do you have a test file for poly-polygons?

**Comment by tbluemel** [comment]
I tried these: http://all-free-download.com/free-vector/download/vector_material_elements_of_classic_cars_721.html

They look really good

**Comment by zoehneto** [comment]
I just tested this file: http://www.parramattatm.org.au/Site/Exec/Speechcraft/Flip%20Charts.rtf
It seems that the bkcolor shouldn't be used for the fill color of graphics objects, because if I remove that part, everything is displayed correctly.

**Comment by zoehneto** [comment]
According to the spec it is only used for text background color.

**Comment by tbluemel** [comment]
Yeah I noticed there are also a few instances in that fancy rtf where it used red as background in a few boxes in some of the charts.

**Comment by tbluemel** [comment]
I added support for opaque text output, which is now the only thing that uses the text background color.

**Comment by tbluemel** [comment]
I will close this bug for now because it seems like most things render pretty well.  It's not a complete implementation and there's probably still plenty of features missing, but we'll add these as we encounter them.
