### ISSUE TITLE
Bullet Points (ListTable) not supported

### ISSUE THREAD

**Issue by cspmosh** [tbluemel/rtf.js#43]
Doesn't appear that bullet points are supported. I get a blank response back with no HTML elements, even for the stuff that isn't part of the bullet points.

**Comment by cspmosh** [comment]
'{\\rtf1\\ansi\\ansicpg1252\\uc1\\deff0{\\fonttbl\x0d\x0a{\\f0\\fnil\\fcharset0\\fprq2 Arial;}\x0d\x0a{\\f1\\fnil\\fcharset1\\fprq2 Arial;}\x0d\x0a{\\f2\\froman\\fcharset0\\fprq2 Georgia;}\x0d\x0a{\\f3\\froman\\fcharset2\\fprq2 Symbol;}}\x0d\x0a{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;\\red51\\green51\\blue51;}\x0d\x0a{\\stylesheet{\\s0\\itap0\\nowidctlpar\\f0\\fs24 [Normal];}{\\*\\cs10\\additive Default Paragraph Font;}{\\s17\\itap0\\nowidctlpar\\sb134\\sa134\\f1\\fs24\\sbasedon0 BODY;}}\x0d\x0a{\\*\\listtable{\\list\\listtemplateid1{\\listlevel\\levelnfc23\\leveljc0\\levelfollow0\\levelstartat1\\levelspace0\\levelindent0{\\leveltext\\''01\\u-3913 ?;}{\\levelnumbers;}\\f3\\fs24\\fbias0\\b0\\i0\\strike0\\ul0\\cf3\\cb0\\fi-360\\li360}{\\listlevel\\levelnfc23\\leveljc0\\levelfollow0\\levelstartat1\\levelspace0\\levelindent0{\\leveltext\\''01\\u-3913 ?;}{\\levelnumbers;}\\f3\\fs24\\fbias0\\b0\\i0\\strike0\\ul0\\cf3\\cb0\\fi-360\\li720}{\\listlevel\\levelnfc23\\leveljc0\\levelfollow0\\levelstartat1\\levelspace0\\levelindent0{\\leveltext\\''01\\u-3913 ?;}{\\levelnumbers;}\\f3\\fs24\\fbias0\\b0\\i0\\strike0\\ul0\\cf3\\cb0\\fi-360\\li1080}{\\listlevel\\levelnfc23\\leveljc0\\levelfollow0\\levelstartat1\\levelspace0\\levelindent0{\\leveltext\\''01\\u-3913 ?;}{\\levelnumbers;}\\f3\\fs24\\fbias0\\b0\\i0\\strike0\\ul0\\cf3\\cb0\\fi-360\\li1440}{\\listlevel\\levelnfc23\\leveljc0\\levelfollow0\\levelstartat1\\levelspace0\\levelindent0{\\leveltext\\''01\\u-3913 ?;}{\\levelnumbers;}\\f3\\fs24\\fbias0\\b0\\i0\\strike0\\ul0\\cf3\\cb0\\fi-360\\li1800}{\\listlevel\\levelnfc23\\leveljc0\\levelfollow0\\levelstartat1\\levelspace0\\levelindent0{\\leveltext\\''01\\u-3913 ?;}{\\levelnumbers;}\\f3\\fs24\\fbias0\\b0\\i0\\strike0\\ul0\\cf3\\cb0\\fi-360\\li2160}{\\listlevel\\levelnfc23\\leveljc0\\levelfollow0\\levelstartat1\\levelspace0\\levelindent0{\\leveltext\\''01\\u-3913 ?;}{\\levelnumbers;}\\f3\\fs24\\fbias0\\b0\\i0\\strike0\\ul0\\cf3\\cb0\\fi-360\\li2520}{\\listlevel\\levelnfc23\\leveljc0\\levelfollow0\\levelstartat1\\levelspace0\\levelindent0{\\leveltext\\''01\\u-3913 ?;}{\\levelnumbers;}\\f3\\fs24\\fbias0\\b0\\i0\\strike0\\ul0\\cf3\\cb0\\fi-360\\li2880}{\\listlevel\\levelnfc23\\leveljc0\\levelfollow0\\levelstartat1\\levelspace0\\levelindent0{\\leveltext\\''01\\u-3913 ?;}{\\levelnumbers;}\\f3\\fs24\\fbias0\\b0\\i0\\strike0\\ul0\\cf3\\cb0\\fi-360\\li3240}{\\listname ;}\\listid1}}\x0d\x0a{\\*\\listoverridetable{\\listoverride\\listid1\\listoverridecount0\\ls1}}\x0d\x0a{\\*\\generator TX_RTF32 15.0.530.503;}\x0d\x0a\\deftab1134\\paperw12240\\paperh15840\\margl0\\margt0\\margr0\\margb0\\widowctrl\\formshade\\sectd\x0d\x0a\\headery720\\footery720\\pgwsxn12240\\pghsxn15840\\marglsxn0\\margtsxn0\\margrsxn0\\margbsxn0{\\pntext\\pard\\plain\\f3\\fs24\\''b7\\tab}\\pard\\itap0\\nowidctlpar\\fi-360\\li360\\tx360\\ls1\\ilvl0{\\*\\pn\\pnlvlblt\\ilvl0\\ls1\\pnstart1\\pnf3\\pnfs24\\pnb0\\pni0\\pnstrike0\\pnulnone\\pncf3\\pncb0{\\pntxtb \\''b7}}\\plain\\f2\\fs24\\cf3 Bullet Point #1\\par{\\pntext\\pard\\plain\\f3\\fs24\\''b7\\tab}\\ls1\\ilvl0{\\*\\pn\\pnlvlblt\\ilvl0\\ls1\\pnstart1\\pnf3\\pnfs24\\pnb0\\pni0\\pnstrike0\\pnulnone\\pncf3\\pncb0{\\pntxtb \\''b7}}Bullet Point #2}'

**Comment by zoehneto** [comment]
It depends on how the bullet points are created. We currently do not support list tables (which contain formatting information for lists which is then referenced by the paragraph), but many rtf files encode the bullet points directly in the paragraph, which we do support. I'm not sure whether missing list table support is the problem here, as I can not open the document as you posted it (can't even be parsed by libreoffice). Could you please upload the actual rtf file or post the pure content on pastebin?

**Comment by cspmosh** [comment]
I was using the RTF string directly in my HTML and that seemed to make a difference. When I tried to load the file with the example application online, it didn't take either and I think it's because of the '\x0d\x0a' line breaks throughout. 

https://pastebin.com/Ev2bR2Up

**Comment by zoehneto** [comment]
How are you using this in html? What you posted is not valid rtf (it is surrounded by quotes and all the backslashes are doubled and even after fixing those it is not valid).

**Comment by cspmosh** [comment]
The single quotes are because it's a javascript string. It renders just fine in the browser using the same format (unless I use bullet points of course). See screenshot below as an example of another rich text string formatted in the same way. 

![2019-08-02_11-59-00](https://user-images.githubusercontent.com/40703038/62386322-160adb00-b51d-11e9-8176-75d75c49aaad.png)

The only thing I can think of is that this is coming from a database and perhaps it's got something to do with that as far as adding the extra backslashes. Did you also replace the \x0d\x0a instances with blank strings? That was the biggest hangup for me when trying to recognize it as valid for the file format.

**Comment by zoehneto** [comment]
The problem is that whatever method you use to create a javascript string out of the rtf file doesn't work properly (your pastebin isn't even a valid javascript string). I have uploaded a fixed version of your rtf file to [pastebin](https://pastebin.com/qLRjuC5a). If you put the contents into a .rtf file you can open that file with your favorite word processor. You can also drag and drop it into our [demo](https://tbluemel.github.io/rtf.js/samples/01_rtf/rtf.html) where you will see the list being rendered correctly:

![image](https://user-images.githubusercontent.com/8282547/62410046-ac540500-b5e0-11e9-97e5-d8a51adc467b.png)
