### ISSUE TITLE
Infinite Loop error

### ISSUE THREAD

**Issue by 8483** [tbluemel/rtf.js#56]
I am trying to use the library in Node, but I can't get it to work...

Here's the [codesandbox](https://codesandbox.io/s/serene-kilby-z7hgi?file=/src/index.js). (The error can be seen here)

Or the code...

```js
const RTFJS = require("rtf.js").RTFJS;

const rtf = `{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1033{\\fonttbl{\\f0\\fnil\\fcharset0 Calibri;}}
    {\\*\\generator Msftedit 5.41.21.2510;}\\viewkind4\\uc1\\pard\\sa200\\sl276\\slmult1\\lang9\\f0\\fs22 This \\fs44 is \\fs22 a \\b simple \\ul one \\i paragraph \\ulnone\\b0 document\\i0 .\\par
    }`;

function stringToArrayBuffer(string) {
  var buffer = new ArrayBuffer(string.length);
  var bufferView = new Uint8Array(buffer);
  for (var i = 0; i < string.length; i++) {
    bufferView[i] = string.charCodeAt(i);
  }
  return buffer;
}

RTFJS.loggingEnabled(false);
// WMFJS.loggingEnabled(false);
// EMFJS.loggingEnabled(false);

const doc = new RTFJS.Document(stringToArrayBuffer(rtf));

const meta = doc.metadata();
doc
  .render()
  .then(function(htmlElements) {
    console.log(meta);
    console.log(htmlElements);
  })
  .catch(error => console.error(error));

```

**Comment by zoehneto** [comment]
There is no error in RTFJS. As the codesandbox message explains, they do static analysis on the files and detect that there *could* be an infinite loop here, there isn't though (the code in question comes from the bundled codepage.js cputils file). If you disable infinite loop detection as described [here](https://codesandbox.io/docs/configuration) it will run without problems.
