### ISSUE TITLE
WMF image not renderer correctly

### ISSUE THREAD

**Issue by ynse01** [tbluemel/rtf.js#58]
The following WMF image is not renderer correctly. The error being displayed is: 
**WMFError: Unexpected end of file**
Same result if I drag it into the live example on GitHub.
I had a quick look at the extensive logging, but couldn't find the cause.

If I open the same image in another viewer (I tried IrfanView), it is displayed correctly. The image is supposed to contain a cooking pot, seen from above.

[Issue Image](https://potlood.github.io/issues/NoDisplay-KookingPot.wmf)

**Comment by zoehneto** [comment]
I have just published a new bugfix version which addresses this issue. I have also adapted the sample pages and our error handling so in the future it will be easier to debug issues by just looking into the browser console.

**Comment by ynse01** [comment]
Thanks @zoehneto , image is shown correctly now
