### ISSUE TITLE
How to fetch email id from rtf file and render in html

### ISSUE THREAD

**Issue by harmeetkhl38** [tbluemel/rtf.js#60]
how to fetch email id from rtf file and render in html

**Comment by zoehneto** [comment]
I need some additional information to answer that. Do you want the email address from the meta information or is it contained within the text? Ideally also provide a sample file showin what you want to do.

**Comment by harmeetkhl38** [comment]
in rtf file  their is email id present along with text.
I need to render the content of the file in html.
Able to render all other text along with sonts and styles but email id is not coming.
Library seems like just emitting that emailid

**Comment by harmeetkhl38** [comment]
> I need some additional information to answer that. Do you want the email address from the meta information or is it contained within the text? Ideally also provide a sample file showin what you want to do.

in rtf file their is email id present along with text.
I need to render the content of the file in html.
Able to render all other text along with sonts and styles but email id is not coming.
Library seems like just emitting that emailid

**Comment by zoehneto** [comment]
I tried to reproduce the issue but it worked for me. You'll have to provide a sample file to debug this further.

**Comment by muditgoel2016** [comment]
![image](https://user-images.githubusercontent.com/18715605/81036792-0a8a7d00-8ebe-11ea-9f96-f2f444fed0bc.png)

**Comment by muditgoel2016** [comment]
You can see above, ths is a copy paste from outlook to a software using rtf.js library..Now I think you understand the issue faced by Harmeet.

**Comment by zoehneto** [comment]
I can see the issue but as I don't have outlook I'll still need a sample file to debug this issue.

**Comment by muditgoel2016** [comment]
Sure....you can have this file I have attached. Extract it to access bcd.rtf that will get you the issue

[bcd.zip](https://github.com/tbluemel/rtf.js/files/4582273/bcd.zip)

**Comment by zoehneto** [comment]
Just for reference: the document uses a sub destination inside \fldinst and \fldrslt (to support both right to left and left to right text), which breaks our field parsing. We probably have to expand our field parsing logic to make it more robust here (not sure this is valid according to the spec, but what can you do).

**Comment by muditgoel2016** [comment]
Is it what is also causing the issue with email etc not appearing? Else, is that separate? Moreover, any plans on the horizon for fixing it? 
Also, I have recently checked even  hyperlinked urls go missing after the content is through rtf.js.

**Comment by zoehneto** [comment]
Yes, that is the cause of the issue. It is also what causes your hyperlink issues, as those use the same underlying feature. I hope to fix this issue as soon as I have time but I can't say when exactly.

**Comment by zoehneto** [comment]
@muditgoel2016 @harmeetkhl38 I have fixed the issue (at least for the sample file you provided) in PR #61 . Could you please test whether this solution solves your problem?

**Comment by muditgoel2016** [comment]
> @muditgoel2016 @harmeetkhl38 I have fixed the issue (at least for the sample file you provided) in PR #61 . Could you please test whether this solution solves your problem?

Yes, it fixes for the use-cases I had mentioned. Thank-you very much!
