### ISSUE TITLE
Unexpected token *

### ISSUE THREAD

**Issue by aprilmariewilson** [tbluemel/rtf.js#65]
I installed rtf.js@3.0.1 to my project and when I try to run my project it fails with a syntax error. 

import * as RTFJS from './dist/RTFJS.bundle';
       ^
SyntaxError: Unexpected token *
I added "type": "module" to my package.json and added --experimental-modules to my start script. 
I changed the version to 2.3.3 
Everything I have attempted I get the same error. Any ideas on what I am doing incorrectly

**Comment by zoehneto** [comment]
Have you tried importing it as described in the [Getting Started Guide](https://github.com/tbluemel/rtf.js/blob/master/GETTING_STARTED.md#importing-rtfjs-as-a-module) (i.e. `import {EMFJS, RTFJS, WMFJS} from 'rtf.js';`)?

**Comment by aprilmariewilson** [comment]
The error is not in the code itself but coming from the rtf.js index file from my node_modules.
/node_modules/rtf.js/index.js:27
import * as RTFJS from './dist/RTFJS.bundle';
 I forgot to mention I am trying to use this in a nest service and not a front end application

**Comment by zoehneto** [comment]
If you want to use the library server side you will have to use jsdom as described [here](https://github.com/tbluemel/rtf.js/blob/master/GETTING_STARTED.md#node-using-jsdom).

**Comment by aprilmariewilson** [comment]
OK thank you for your help. I will look into that
