### ISSUE TITLE
Converting an RTF that was copied from an outlook body where an apostrophe (') and images results in loss of the apostrophes

### ISSUE THREAD

**Issue by xtenpeben** [tbluemel/rtf.js#69]
For example, if you have an e-mail with texts like the one below:

Hello, I'm new to this. <this text is followed by images>

The converted html has the text and images but the apostrophe is lost. 

Result: Hello, Im new to this. <images>

**Comment by zoehneto** [comment]
Please provide a sample file so I can debug the issue further.

**Comment by vikkrantxx7** [comment]
Here apostrophe is lost.
Original-
![image](https://user-images.githubusercontent.com/37444378/99957262-67dc1200-2dad-11eb-840a-0e9513161e6c.png)

Converted-
![image](https://user-images.githubusercontent.com/37444378/99957211-50048e00-2dad-11eb-94ff-50558aefc63d.png)

File-
[word pad pic link.zip](https://github.com/tbluemel/rtf.js/files/5582610/word.pad.pic.link.zip)
