### ISSUE TITLE
Cannot read property 'dec' of undefined

### ISSUE THREAD

**Issue by vikkrantxx7** [tbluemel/rtf.js#71]
This comes from Parser.js inside summarizeText
`cptable[codepage].dec`

Just migrated to Webpack 5 and this error showed up.
I think somehow cptable is not resolving.

**Comment by zoehneto** [comment]
cptable is bundled in with our library so it should work. Without a minimal reproducing example I can't help you here.

**Comment by vikkrantxx7** [comment]
So I dug down and found out that cptable is already present in global scope so the control doesn't go in-
---RTFJS.bundle.js---
`if(typeof cptable === "undefined") {` line-1044
and the default export is never assigned-
`if ( true && module.exports && typeof DO_NOT_EXPORT_CODEPAGE === 'undefined') module.exports = factory(cpt);` line-1047
So I just added this in the else clause-
```
else { cptable = factory(cptable);
      module.exports = cptable;
  }
``` line- 1050
And now everything worked fine... I don't know why this happened. May be I am missing something due to my limited knowledge on webpack?

**Comment by vikkrantxx7** [comment]
Finally got the reason.
Actually, xlsx library which has codepage as dependency is also imported before rtfjs and creates a global cptable variable.
So the control doesn't go in the above block and the default export is an empty object.
Deleting that global variable before importing rtfjs resolved this.
