### ISSUE TITLE
backslash newline not treated as equivalent to \par

### ISSUE THREAD

**Issue by james-k-polk** [tbluemel/rtf.js#74]
I have some rtf that doesn't appear to parse correctly. Instead of the \par command it has the backslash character just before a newline, or `5c 0a` if you are looking at the file with a hex editor. According to the [Microsoft RTF specification](https://www.biblioscape.com/rtf15_spec.htm) (search for the word "carriage" to find it):

> A carriage return (character value 13) or linefeed (character value 10) will be treated as a \par control if the character is preceded by a backslash. You must include the backslash; otherwise, RTF ignores the control word.

Not sure if this is a limitation of rtf.js or a bug somewhere in my rtf document or code but it appears that these are ignored.

**Comment by zoehneto** [comment]
We don't handle this case right now and it seems to be more of an edge case (of the documents used for testing, none seem to take advantage of this feature). Nonetheless it seems straightforward to implement this behaviour and I have code for it but I'll need a sample document to verify it actually works as intended.

**Comment by james-k-polk** [comment]
Thanks, a zip file with the sample rtf is attached. Apparently github doesn't support rtf attachments.
[example.zip](https://github.com/tbluemel/rtf.js/files/5761654/example.zip)
