### ISSUE TITLE
Error when parsing rtf file with spaces in colortbl definition

### ISSUE THREAD

**Issue by MooDySmiles** [tbluemel/rtf.js#81]
Hi! Thanks for this wonderful plugin.

Today I encountered some problems in parsing some RTF files.
Ended up finding out that the problem lies in the definition of the `colortbl` property.

At some point, for not known reason, after the closing semicolon of a `colordef`, a white space is present. This generate the parsing error of the file.

I tested the plugin [here](https://tbluemel.github.io/rtf.js/samples/01_rtf/rtf.html) with both versions of the file (with and without the whitespace), and only the one without the whitespace works.

Then I tested both files on several websites (like [this](https://products.groupdocs.app/editor/rtf) one), and both versions were rendered correctly.

**Comment by zoehneto** [comment]
Thank you for your bug report. Could you please provide a sample document which triggers this issue?

**Comment by MooDySmiles** [comment]
Yes, sorry. I had the zip file ready to attach, but I forgot about it :sweat_smile: 

[rtf with spaces in colortbl definition.zip](https://github.com/tbluemel/rtf.js/files/6237398/rtf.with.spaces.in.colortbl.definition.zip)

Inside there are two rtf files, one without whitespaces and the other one with whitespaces in the `colortbl` property.
