### ISSUE TITLE
Issue rendering images

### ISSUE THREAD

**Issue by djdannycastillo** [tbluemel/rtf.js#90]
Hi there, 

I have an issue trying to load a RTF with image. I'm getting this error message in log: 
`findParentDestination() did not find destination pict-group`

Does anyone knows what's happening?

The rest of the text is rendering fine, just the image doesn't load. Also, I'm using the online sample (https://tbluemel.github.io/rtf.js/samples/01_rtf/rtf.html)

Bellow a little fragment of the code:
`{\rtf1\ansi\ansicpg1252\uc1\deff0\adeff0\deflang0\deflangfe0\adeflang0{\fonttbl
{\f0\fswiss\fcharset0\fprq2{\*\panose 020B0604020202020204}Arial;}
{\f1\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}}
{\colortbl;\red0\green0\blue0;}
{\stylesheet{\s0\ltrpar\itap0\nowidctlpar\ql\li0\ri0\lin0\rin0\cbpat0\rtlch\af0\afs24\ltrch\f0\fs24 [Normal];}{\*\cs10\additive Default Paragraph Font;}}
{\info
{\*\txInfo{\txVer 25.0.721.500}}}
\paperw15000\paperh15840\margl1440\margt1440\margr1440\margb1440\deftab1134\widowctrl\lytexcttp\formshade\viewbksp1
{\*\background{\shp{\*\shpinst\shpleft0\shptop0\shpright0\shpbottom0\shpfhdr0\shpbxmargin\shpbxignore\shpbymargin\shpbyignore\shpwr0\shpwrk0\shpfblwtxt1\shplid1025{\sp{\sn shapeType}{\sv 1}}{\sp{\sn fFlipH}{\sv 0}}{\sp{\sn fFlipV}{\sv 0}}{\sp{\sn fillColor}{\sv 16777215}}{\sp{\sn fFilled}{\sv 1}}{\sp{\sn lineWidth}{\sv 0}}{\sp{\sn fLine}{\sv 0}}{\sp{\sn fBackground}{\sv 1}}{\sp{\sn fLayoutInCell}{\sv 1}}}}}\sectd
\headery720\footery720\pgwsxn15000\pghsxn15840\marglsxn1440\margtsxn1440\margrsxn1440\margbsxn1440\pgbrdropt0\pard\ltrpar\itap0\nowidctlpar\ql\li0\ri0\lin0\rin0\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\tx9360\tx10080\plain\rtlch\af0\afs20\alang0\ltrch\f0\fs20\lang0\langnp0\langfe0\langfenp0 ---------------------\par From: JHON DOE USER \par To: XZTEST, RYAN  \par Sent: 06/02/2022 11:52:28 MDT\par Subject: rtf - image in line  \par\pard\ltrpar\itap0\nowidctlpar\ql\li0\ri0\lin0\rin0\plain\rtlch\af0\afs20\alang0\acf1\ltrch\f0\fs20\lang1024\langfe1024\langnp0\langfenp0\noproof\cf1{\txfielddef{\*\txfieldstart\txfieldtype0\txfieldflags147\txfielddataval1\txfielddata 30007800640034003600390061003100660033000000}{\*\txfieldtext \par {\*\txfieldend}}\par }\plain\rtlch\af0\afs20\alang1033\acf1\ltrch\f0\fs20\lang1033\langnp1033\langfe1033\langfenp1033\cf1{\pict{\*\picprop{\sp{\sn shapeType}{\sv 75}}{\sp{\sn fFlipH}{\sv 0}}{\sp{\sn fFlipV}{\sv 0}}{\sp{\sn wzName}{\sv _tx_id_1_}}{\sp{\sn fLayoutInCell}{\sv 1}}}\wmetafile8\picw14764\pich5636\picwgoal8370\pichgoal3195\picscalex100\picscaley100\blipupi96 
01000900000378b9020000005db902000000050000000b0200000000050000000c02d5002e02050000000701040000005db9
020040092000cc0000000000d5002e0200000000280000002e020000d500000001001800000000007c720500000000000000
00000000000000000000329ffb329ffb329ffb329ffb329ffb329ffb329ffb329ffb329ffb329ffb329ffb329ffb329ffb32.....`

**Comment by zoehneto** [comment]
To be able to debug this issue I need a complete valid RTF file (your file seems to contain a WMF picture and the binary is simply cut off).

**Comment by djdannycastillo** [comment]
This is the link with the file: https://drive.google.com/file/d/1DUltdVfpjyqRpRH24qDvOwHD4w5gaSKe/view?usp=sharing
