### ISSUE TITLE
How here works images?

### ISSUE THREAD

**Issue by mamonovv** [tbluemel/rtf.js#91]
I going throw your GETTING STARTED and library works fine only for text, it can't see images. Looking throw code example i see only onPicture setting, that doesn`t working at all, cuz console.logs in here never calling.
Can you explain me, and later for all in getting started how to use your good library with images?

**Comment by mamonovv** [comment]
Thanks for your fast answer. I test my file in this example and here the same problem, no image. I can share my file, for your tests and debugging.
[example.zip](https://github.com/tbluemel/rtf.js/files/9108867/example.zip)

**Comment by zoehneto** [comment]
The problem here is that the image is wrapped in an office 97 to office 2007 shape (the `\shp` in your file), which we currently don't support. If you can influence the rtf file so the image is included directly, it will be displayed, otherwise someone would have to add support for shapes.
