### ISSUE TITLE
Some fonts are not correctly shown

### ISSUE THREAD

**Issue by nickchen120235** [tbluemel/rtf.js#95]
## Description
When the rtf file contains fonts whose name are not ASCIIs, they are incorrectly parsed (and therefore incorrectly shown).

## Reproduce
Load [this file](https://docs.google.com/document/d/1T3ljJ6tQojZL_cxsp7CpIcMioap2eJb0zyQnzU4tPdE/edit?usp=sharing) into the RTF demo page and check the logs.

```
[fonttbl][42] index = ¼Ð·¢Åé; alternative: null
[fonttbl][44] index = @¼Ð·¢Åé; alternative: null
```

## Expected 
The logs should be

```
[fonttbl][42] index = 標楷體; alternative: null
[fonttbl][44] index = @標楷體; alternative: null
```

**Comment by zoehneto** [comment]
When I download the RTF from Google docs it works as expected, can you attach the file giving you issues directly to this issue?

**Comment by nickchen120235** [comment]
Sure but unfortunately uploading rtf files aren't supported by GitHub, so I copied the entire content into [this gist](https://gist.github.com/nickchen120235/5ad893f09eed591a537a26da534e4fea).
